import React from "react";
import {
  AisleArrival,
  ButtonArrival,
  Column2Arrival,
  ColumnArrival,
  ReferentSeatArrival,
  RowArrival,
  SeatSelectArrival,
  SubtittleArrival,
} from "./StyleSeatSelectionArrival";
import { StyleBottonArrivals, StyledContainerArrival, StyledDateArrival } from "../arrivalsFlights/StylesArrivalsFlight";

const SeatSelectionArrival = () => {
  return (
    <>
     <StyledDateArrival>
        <StyledContainerArrival>
        <h1>Vuelo de Regreso</h1>
        <StyleBottonArrivals>Cambiar vuelo</StyleBottonArrivals>
        </StyledContainerArrival>
        <h2>Lunes 11 sept 2023</h2>
        <h4>San Andres, Colombia(ADZ)</h4>
        <p>Selección de horarios y equipaje</p>
      </StyledDateArrival>
      
      <ReferentSeatArrival>
        <ColumnArrival>
          <RowArrival>
            <AisleArrival>A</AisleArrival>
            <AisleArrival>B</AisleArrival>
            <AisleArrival>C</AisleArrival>
          </RowArrival>
        </ColumnArrival>
        <ColumnArrival>
          <AisleArrival></AisleArrival>
        </ColumnArrival>
        <ColumnArrival>
          <RowArrival>
            <AisleArrival>D</AisleArrival>
            <AisleArrival>E</AisleArrival>
            <AisleArrival>F</AisleArrival>
          </RowArrival>
        </ColumnArrival>
      </ReferentSeatArrival>
      <SubtittleArrival>
        <h5>Salida Segura</h5>
      </SubtittleArrival>
      <SeatSelectArrival>
        <ColumnArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
        </ColumnArrival>
        <Column2Arrival>
          <AisleArrival>1</AisleArrival>
          <AisleArrival>3</AisleArrival>
          <AisleArrival>4</AisleArrival>
          <AisleArrival>2</AisleArrival>
          <AisleArrival>5</AisleArrival>
        </Column2Arrival>
        <ColumnArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
        </ColumnArrival>
      </SeatSelectArrival>
      <SubtittleArrival>
        <h5>Estándar</h5>
      </SubtittleArrival>
      <SeatSelectArrival>
        <ColumnArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
        </ColumnArrival>
        <Column2Arrival>
          <AisleArrival>6</AisleArrival>
          <AisleArrival>7</AisleArrival>
          <AisleArrival>8</AisleArrival>
          <AisleArrival>9</AisleArrival>
          <AisleArrival>10</AisleArrival>
        </Column2Arrival>
        <ColumnArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
          <RowArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
            <ButtonArrival></ButtonArrival>
          </RowArrival>
        </ColumnArrival>
      </SeatSelectArrival>
    </>
  );
};

export default SeatSelectionArrival;
