import React from "react";
import {
  StyleBottonDeparture,
  StyledContainer,
  StyledDate,
} from "../departureFlight/StylesDeparture";
import {
  Aisle,
  Button,
  Column,
  Column2,
  ReferenSeat,
  Row,
  SeatDeparture,
  SeatSelect,
  Subtittle,
} from "./StyleSeatSelectionDeparture";

const SeatSelectionDeparture = () => {
  return (
    <>
    <SeatDeparture>
      <StyledDate>
        <StyledContainer>
          <h1>Vuelo de Salida</h1>
          <StyleBottonDeparture>Cambiar vuelo</StyleBottonDeparture>
        </StyledContainer>
        <h2>Jueves 20 jul 2023</h2>
        <h4>Medellín, Colombia(MDE)</h4>
        <p>Selecciona tus asientos</p>
      </StyledDate>
      <ReferenSeat>
        <Column>
          <Row>
            <Aisle>A</Aisle>
            <Aisle>B</Aisle>
            <Aisle>C</Aisle>
          </Row>
        </Column>
        <Column>
          <Aisle></Aisle>
        </Column>
        <Column>
          <Row>
            <Aisle>D</Aisle>
            <Aisle>E</Aisle>
            <Aisle>F</Aisle>
          </Row>
        </Column>
      </ReferenSeat>
      <Subtittle><h5>Salida Segura</h5></Subtittle>
      <SeatSelect>
        <Column>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
        </Column>
          <Column2>
            <Aisle>1</Aisle>
            <Aisle>2</Aisle>
            <Aisle>3</Aisle>
            <Aisle>4</Aisle>
            <Aisle>5</Aisle>
            
          </Column2>
        <Column>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
        </Column>
      </SeatSelect>
      <Subtittle><h5>Estándar</h5></Subtittle>
      <SeatSelect>
        <Column>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
        </Column>
          <Column2>
            <Aisle>6</Aisle>
            <Aisle>7</Aisle>
            <Aisle>8</Aisle>
            <Aisle>9</Aisle>
            <Aisle>10</Aisle>
          </Column2>
        <Column>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
          <Row>
            <Button></Button>
            <Button></Button>
            <Button></Button>
          </Row>
        </Column>
      </SeatSelect>
      </SeatDeparture>
    </>
  );
};

export default SeatSelectionDeparture